from product_class import Products
from store_class import Store

store1 = Store('Store 1')
store2 = Store('Store 2')
store3 = Store('Store 3')
store4 = Store('Store 4')

product1 = Products('abc', 10, 'a')
product2 = Products('def', 20, 'a')
product3 = Products('asd', 30, 'a')
product4 = Products('qwe', 40, 'b')
product5 = Products('ert', 50, 'b')
product6 = Products('rty', 60, 'b')
product7 = Products('tyu', 70, 'b')
product8 = Products('yui', 80, 'c')
product9 = Products('uio', 90, 'c')
product10 = Products('dfg', 10, 'c')

store1.add_product(product1)
store1.add_product(product2)
store1.add_product(product3)
store1.add_product(product4)
store1.add_product(product5)
store1.add_product(product6)
store1.add_product(product7)
store1.add_product(product8)
store1.add_product(product9)
store1.add_product(product10)

store1.sell_product(1)
store1.inflation(.02)
store1.set_clearance('b',.3)

product1.print_info()
product2.print_info()
product3.print_info()
product4.print_info()
product5.print_info()
product6.print_info()
product7.print_info()
product8.print_info()
product9.print_info()
product10.print_info()